# AI Assignment 
## ID = 123124301

In [4]:
#Import the libraries I need
import pandas as pd
import numpy as np

from pandas.plotting import scatter_matrix
from seaborn import scatterplot, heatmap

from sklearn.model_selection import train_test_split

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler

from sklearn.preprocessing import OneHotEncoder

from sklearn.base import BaseEstimator, TransformerMixin

from sklearn.linear_model import Ridge
from sklearn.neighbors import KNeighborsRegressor

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_validate

from sklearn.metrics import mean_absolute_error

from joblib import dump

## I first want to look at the dataset, get a picture of what I am working with.

In [5]:
df = pd.read_csv(r"C:\Users\raula\Desktop\facultate\anul 2 sem 1\Artificial Intelligence 1\artificial_intelligence_2023_2024\artificial_intelligence_2023_2024\ai1\datasets\dataset_reoffending.csv")

# Shuffle the dataset
df = df.sample(frac=1, random_state=2)
df.reset_index(drop=True, inplace=True)

In [7]:
df.shape

(25835, 53)

In [31]:
df.describe(include="all")

,id,gender,race,age,address,gang_affiliated,risk_score,supervision_level,education_level,dependents,...,cocaine_positive_tests,meth_positive_tests,other_positive_tests,days_employed,jobs_per_year,employment_exempt,reoffended_within_3_years,reoffended_in_year_1,reoffended_in_year_2,reoffended_in_year_3
count,25835.000000,25835,25835,25835,25835.000000,22668,25360.000000,24115,25835,25835,...,20663.000000,20663.000000,20663.00000,25373.000000,25027.000000,25835,25835,25835,25835,25835
unique,NaN,2,2,7,NaN,2,NaN,3,3,4,...,NaN,NaN,NaN,NaN,NaN,2,2,2,2,2
top,NaN,M,black,23-27,NaN,False,NaN,Standard,High School Diploma,0,...,NaN,NaN,NaN,NaN,NaN,False,True,False,False,False
freq,NaN,22668,14847,5176,NaN,18730,NaN,9983,11390,8037,...,NaN,NaN,NaN,NaN,NaN,22399,14904,18111,21268,23222
mean,13314.004838,NaN,NaN,NaN,12.361796,NaN,6.082216,NaN,NaN,NaN,...,0.013741,0.012890,0.00755,0.482331,0.769295,NaN,NaN,NaN,NaN,NaN
std,7722.206327,NaN,NaN,NaN,7.133742,NaN,2.381442,NaN,NaN,NaN,...,0.061233,0.060581,0.04115,0.425004,0.813787,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,1.000000,NaN,1.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.00000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN
25%,6626.500000,NaN,NaN,NaN,6.000000,NaN,4.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.00000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN
50%,13270.000000,NaN,NaN,NaN,12.000000,NaN,6.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.00000,0.475728,0.635217,NaN,NaN,NaN,NaN,NaN
75%,20021.500000,NaN,NaN,NaN,18.000000,NaN,8.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.00000,0.969325,1.000000,NaN,NaN,NaN,NaN,NaN
max,26761.000000,NaN,NaN,NaN,25.000000,NaN,10.000000,NaN,NaN,NaN,...,1.000000,1.000000,1.00000,1.000000,8.000000,NaN,NaN,NaN,NaN,NaN

What i find interesting here is the most subjects are **males**, **black**, and between **age 23-27** and also not with a **high education**

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25835 entries, 0 to 25834
Data columns (total 53 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   id                                    25835 non-null  int64
 1   gender                                25835 non-null  object
 2   race                                  25835 non-null  object
 3   age                                   25835 non-null  object
 4   address                               25835 non-null  int64
 5   gang_affiliated                       22668 non-null  object
 6   risk_score                            25360 non-null  float64
 7   supervision_level                     24115 non-null  object
 8   education_level                       25835 non-null  object
 9   dependents                            25835 non-null  object
 10  offence                               22558 non-null  object
 11  years_in_prison                       25835 non-null  object
 12  felony_arrests                        25835 non-null  object
 13  misdemeanor_arrests                   25835 non-null  object
 14  violence_arrests                      25835 non-null  object
 15  property_arrests                      25835 non-null  object
 16  drug_arrests                          25835 non-null  object
 17  parole_violation_arrests              25835 non-null  object
 18  domestic_violence_arrests             25835 non-null  bool
 19  gun_arrests                           25835 non-null  bool
 20  felony_convictions                    25835 non-null  object
 21  misdemeanor_convictions               25835 non-null  object
 22  violence_convictions                  25835 non-null  bool
 23  property_convictions                  25835 non-null  object
 24  drug_convictions                      25835 non-null  object
 25  parole_violation_convictions          25835 non-null  bool
 26  domestic_violence_convictions         25835 non-null  bool
 27  gun_convictions                       25835 non-null  bool
 28  parole_revocations                    25835 non-null  bool
 29  probation_revocations                 25835 non-null  bool
 30  mh_sa_programme                       25835 non-null  bool
 31  cs_programme                          25835 non-null  bool
 32  other_condition                       25835 non-null  bool
 33  electronic_monitoring_violations      25835 non-null  bool
 34  instruction_following_violations      25835 non-null  bool
 35  failure_to_report_violations          25835 non-null  bool
 36  moving_without_permission_violations  25835 non-null  bool
 37  num_delinquency_reports               25835 non-null  object
 38  num_program_attendances               25835 non-null  object
 39  num_unexcused_absences                25835 non-null  object
 40  num_residence_changes                 25835 non-null  object
 41  days_between_drug_tests               19732 non-null  float64
 42  marijuana_positive_tests              20663 non-null  float64
 43  cocaine_positive_tests                20663 non-null  float64
 44  meth_positive_tests                   20663 non-null  float64
 45  other_positive_tests                  20663 non-null  float64
 46  days_employed                         25373 non-null  float64
 47  jobs_per_year                         25027 non-null  float64
 48  employment_exempt                     25835 non-null  bool
 49  reoffended_within_3_years             25835 non-null  bool
 50  reoffended_in_year_1                  25835 non-null  bool
 51  reoffended_in_year_2                  25835 non-null  bool
 52  reoffended_in_year_3                  25835 non-null  bool
dtypes: bool(20), float64(8), int64(2), object(23)
memory usage: 7.0+ MB

There are a lot of features, but also a lot of which I would like to get a clue what are they made from so I will continue with that.

In [34]:
print("gang_affiliated = ", df["gang_affiliated"].unique())
print("supervision_level = " , df["supervision_level"].unique())
print("education_level = ",df["education_level"].unique())
print("dependents = ", df["dependents"].unique())
print("offence = ", df["offence"].unique())
print("years_in_prison = ", df["years_in_prison"].unique())
print("felony_arrests = ", df["felony_arrests"].unique())
print("violence_arrests = ", df["violence_arrests"].unique())
print("property_arrests = ", df["property_arrests"].unique())
print("drug_arrests = ", df["drug_arrests"].unique())
print("parole_violation_arrests = ", df["parole_violation_arrests"].unique())
print("domestic_violence_arrests = ", df["domestic_violence_arrests"].unique())
print("gun_arrests = ", df["gun_arrests"].unique())
print("felony_convictions = ", df["felony_convictions"].unique())
print("misdemeanor_convictions  = ", df["misdemeanor_convictions"].unique())
print("property_convictions = ", df["property_convictions"].unique())
print("parole_revocations = ", df["parole_revocations"].unique())
print("probation_revocations = ", df["probation_revocations"].unique())
print("other_condition = ", df["other_condition"].unique())
print("num_delinquency_reports = ", df["num_delinquency_reports"].unique())
print("reoffended_in_year_3 = ", df["reoffended_in_year_3"].unique())

gang_affiliated =  [nan False True]
supervision_level =  ['High' 'Standard' 'Specialized' nan]
education_level =  ['At least some college' 'High School Diploma' 'Less than HS diploma']
dependents =  ['3 or more' '0' '2' '1']
offence =  ['Property' 'Violent/Non-Sex' nan 'Other' 'Drug' 'Violent/Sex']
years_in_prison =  ['Less than 1 year' '1-2 years' 'More than 3 years'
 'Greater than 2 to 3 years']
felony_arrests =  ['3' '5' '2' '4' '6' '10 or more' '9' '0' '7' '1' '8']
violence_arrests =  ['0' '3 or more' '2' '1']
property_arrests =  ['2' '5 or more' '1' '4' '3' '0']
drug_arrests =  ['1' '0' '3' '4' '2' '5 or more']
parole_violation_arrests =  ['2' '4' '5 or more' '0' '3' '1']
domestic_violence_arrests =  [False  True]
gun_arrests =  [False  True]
felony_convictions =  ['1' '2' '0' '3 or more']
misdemeanor_convictions  =  ['1' '4 or more' '0' '3' '2']
property_convictions =  ['1' '3 or more' '0' '2']
parole_revocations =  [False  True]
probation_revocations =  [False  True]
other_condition =  [ True False]
num_delinquency_reports =  ['0' '4 or more' '3' '1' '2']
reoffended_in_year_3 =  [False  True]

So far I have drawn some conclusions about the next:

* **felony_arrests** -> we have a wide variety and I would like afterwards to see how felony_arrests plots with reoffences that happened in 3 years
* **other_condition** -> other, including no electronic monitoring, enrolment on a sex offender programme or no victim contact
* **days_employed** and **jobs_per_year** -> might be good indicators towards reoffending or not
* **drug tests** -> have foat values associated with them

There are also a lot of features like arrest, convictions, violations, drug tests that I think will be in close relationship with the probability of reoffending or not
Also, as seen above there are feature with nan values so I need to see what I do with them, if I leave them, change them or drop them.

In [40]:
#Because we are only asked to predict reoffending within three years I will drop the other columns I am not interested in 
df = df.drop(labels=["reoffended_in_year_1", "reoffended_in_year_2", "reoffended_in_year_3"],axis=1)

In [41]:
df.shape

(25835, 50)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25835 entries, 0 to 25834
Data columns (total 50 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   id                                    25835 non-null  int64
 1   gender                                25835 non-null  object
 2   race                                  25835 non-null  object
 3   age                                   25835 non-null  object
 4   address                               25835 non-null  int64
 5   gang_affiliated                       22668 non-null  object
 6   risk_score                            25360 non-null  float64
 7   supervision_level                     24115 non-null  object
 8   education_level                       25835 non-null  object
 9   dependents                            25835 non-null  object
 10  offence                               22558 non-null  object
 11  years_in_prison                       25835 non-null  object
 12  felony_arrests                        25835 non-null  object
 13  misdemeanor_arrests                   25835 non-null  object
 14  violence_arrests                      25835 non-null  object
 15  property_arrests                      25835 non-null  object
 16  drug_arrests                          25835 non-null  object
 17  parole_violation_arrests              25835 non-null  object
 18  domestic_violence_arrests             25835 non-null  bool
 19  gun_arrests                           25835 non-null  bool
 20  felony_convictions                    25835 non-null  object
 21  misdemeanor_convictions               25835 non-null  object
 22  violence_convictions                  25835 non-null  bool
 23  property_convictions                  25835 non-null  object
 24  drug_convictions                      25835 non-null  object
 25  parole_violation_convictions          25835 non-null  bool
 26  domestic_violence_convictions         25835 non-null  bool
 27  gun_convictions                       25835 non-null  bool
 28  parole_revocations                    25835 non-null  bool
 29  probation_revocations                 25835 non-null  bool
 30  mh_sa_programme                       25835 non-null  bool
 31  cs_programme                          25835 non-null  bool
 32  other_condition                       25835 non-null  bool
 33  electronic_monitoring_violations      25835 non-null  bool
 34  instruction_following_violations      25835 non-null  bool
 35  failure_to_report_violations          25835 non-null  bool
 36  moving_without_permission_violations  25835 non-null  bool
 37  num_delinquency_reports               25835 non-null  object
 38  num_program_attendances               25835 non-null  object
 39  num_unexcused_absences                25835 non-null  object
 40  num_residence_changes                 25835 non-null  object
 41  days_between_drug_tests               19732 non-null  float64
 42  marijuana_positive_tests              20663 non-null  float64
 43  cocaine_positive_tests                20663 non-null  float64
 44  meth_positive_tests                   20663 non-null  float64
 45  other_positive_tests                  20663 non-null  float64
 46  days_employed                         25373 non-null  float64
 47  jobs_per_year                         25027 non-null  float64
 48  employment_exempt                     25835 non-null  bool
 49  reoffended_within_3_years             25835 non-null  bool
dtypes: bool(17), float64(8), int64(2), object(23)
memory usage: 6.9+ MB

In [44]:
#Now I want to separate the featuers so it will be easier to manipulate them 
numeric_features = ["id", "address", "risk_score", "days_between_drug_tests", "marijuana_positive_tests", "cocaine_positive_tests",
                   "meth_positive_tests", "other_positive_tests", "days_employed", "jobs_per_year"]
nominal_features = ["gender", "race", "age", "gang_affiliated", "supervision_level", "education_level", "dependents", "offence",
                   "years_in_prison", "felony_arrests", "misdemeanor_arrests", "violence_arrests", "property_arrests", "drug_arrests",
                   "parole_violation_arrests", "felony_convictions", "misdemeanor_convictions", "property_convictions", "drug_convictions",
                   "num_delinquency_reports", "num_program_attendances", "num_unexcused_absences", "num_residence_changes"]
boolean_features = ["domestic_violence_arrests", "gun_arrests", "violence_convictions", "parole_violation_convictions", "domestic_violence_convictions",
                   "gun_convictions", "parole_revocations", "probation_revocations", "mh_sa_programme", "cs_programme", "other_condition",
                   "electronic_monitoring_violations", "instruction_following_violations", "failure_to_report_violations", "moving_without_permission_violations",
                   "employment_exempt"] #reoffended_within_3_years this is our y so I won't add it here
print(len(numeric_features), len(nominal_features), len(boolean_features)) #just to check I didn't miss anythign

10 23 16

#### Before I start to visualize data I should look at values like NaN and decide what to do with them, also I should look like values that don't seem right

In [47]:
#First for numeric features
df[numeric_features].describe(include="all")

,id,address,risk_score,days_between_drug_tests,marijuana_positive_tests,cocaine_positive_tests,meth_positive_tests,other_positive_tests,days_employed,jobs_per_year
count,25835.000000,25835.000000,25360.000000,19732.000000,20663.000000,20663.000000,20663.000000,20663.00000,25373.000000,25027.000000
mean,13314.004838,12.361796,6.082216,93.890044,0.063350,0.013741,0.012890,0.00755,0.482331,0.769295
std,7722.206327,7.133742,2.381442,117.169847,0.138453,0.061233,0.060581,0.04115,0.425004,0.813787
min,1.000000,1.000000,1.000000,0.500000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,6626.500000,6.000000,4.000000,28.837366,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,13270.000000,12.000000,6.000000,55.424812,0.000000,0.000000,0.000000,0.00000,0.475728,0.635217
75%,20021.500000,18.000000,8.000000,110.333333,0.071429,0.000000,0.000000,0.00000,0.969325,1.000000
max,26761.000000,25.000000,10.000000,1088.500000,1.000000,1.000000,1.000000,1.00000,1.000000,8.000000

In [48]:
df[numeric_features].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25835 entries, 0 to 25834
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        25835 non-null  int64
 1   address                   25835 non-null  int64
 2   risk_score                25360 non-null  float64
 3   days_between_drug_tests   19732 non-null  float64
 4   marijuana_positive_tests  20663 non-null  float64
 5   cocaine_positive_tests    20663 non-null  float64
 6   meth_positive_tests       20663 non-null  float64
 7   other_positive_tests      20663 non-null  float64
 8   days_employed             25373 non-null  float64
 9   jobs_per_year             25027 non-null  float64
dtypes: float64(8), int64(2)
memory usage: 2.0 MB